Test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include ('apps.mascota.urls')),
    url(r'^adopcion/', include ('apps.adopcion.urls')),
]

apps/adopcion/urls.py
from __future__ import absolute_import,unicode_literals
from django.conf.urls import url, include

from apps.adopcion.views import index_adopcion


urlpatterns = [
    url(r'^index$', index_adopcion),
]

apps/mascota/urls.py
from __future__ import absolute_import,unicode_literals
from django.conf.urls import url, include

from apps.mascota.views import index_mascota, mascota_view, mascota_list, mascota_edit, mascota_delete, \
    MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

app_name = 'mascota'

# Vistas a base de funciones
# urlpatterns = [
#     url(r'^$',                              index_mascota,  name='index'),
#     url(r'^nuevo$',                         MascotaCreate.as_view(),   name='mascota_crear'),
#     url(r'^listar$',                        MascotaList.as_view(),   name='mascota_listar'),
#     url(r'^editar/(?P<id_mascota>\d+)/$',   mascota_edit,   name='mascota_editar'),
#     url(r'^eliminar/(?P<id_mascota>\d+)/$', mascota_delete, name='mascota_eliminar'),
# ]

# Vistas a base de clases
urlpatterns = [
    url(r'^$',                              index_mascota,  name='index'),
    url(r'^nuevo$',                         MascotaCreate.as_view(),   name='mascota_crear'),
    url(r'^listar',                        MascotaList.as_view(),   name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$',           MascotaUpdate.as_view(),   name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$',         MascotaDelete.as_view(), name='mascota_eliminar'),
]

apps/adopcion/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Persona(models.Model):

    nombre      = models.CharField(max_length=50)
    apellidos   = models.CharField(max_length=70)
    edad        = models.IntegerField()
    telefono    = models.CharField(max_length=12)
    email       = models.EmailField()
    domicilio   = models.TextField()
    
    #Sirve para traer los datos no el objeto
    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellidos)

apps/mascota/models.py
from __future__ import absolute_import,unicode_literals

from django.db import models
from apps.adopcion.models import Persona

# Create your models here.

class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre)

class Mascota(models.Model):

    nombre          = models.CharField(max_length=50)
    sexo            = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate   = models.DateField()


    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna  = models.ManyToManyField(Vacuna, blank=True) 

apps/mascota/forms.py
from __future__ import absolute_import,unicode_literals
from django import forms

from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):
    
    class Meta:
        model = Mascota

        fields = [
            'nombre',
            'edad_aproximada',
            'sexo',
            'fecha_rescate',
            'persona',
            'vacuna',
        ]

        labels = {
            'nombre':           'Nombre',
            'edad_aproximada':  'Edad Aproximada',
            'sexo':             'Sexo',
            'fecha_rescate':    'Fecha Rescate',
            'persona':          'Adoptante',
            'vacuna':           'Vacunas',
        }

        widgets = {
            'nombre':               forms.TextInput(attrs={'class':'forms-control'}),
            'edad_aproximada':      forms.TextInput(attrs={'class':'forms-control'}),
            'sexo':                 forms.TextInput(attrs={'class':'forms-control'}),
            'fecha_rescate':        forms.TextInput(attrs={'class':'forms-control'}),
            'persona':              forms.Select(attrs={'class':'forms-control'}),
            'vacuna':               forms.CheckboxSelectMultiple(),
        }

apps/adopcion/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

# Create your views here.

def index_adopcion(request):
        return HttpResponse("Estas en adopcion")

apps/mascota/views.py
from __future__ import absolute_import,unicode_literals
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.mascota.forms  import MascotaForm
from apps.mascota.models import Mascota

# Create your views here.
# Vistas basadas en funciones

def index_mascota(request):
    return render(request, 'mascota/index.html')

#Guardar Datos
def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota:index')
    else:
        form = MascotaForm()
    
    return render(request, 'mascota/mascota_form.html', {'form':form})

#Listar Datos
def mascota_list(request):
    mascota  = Mascota.objects.all().order_by('id')
    contexto = {'mascotas':mascota}
    return render(request, 'mascota/mascota_list.html', contexto) 

#Editar Datos
def mascota_edit(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_form.html', {'form':form})

#Eliminar Datos
def mascota_delete(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})

#Vistas basadas en clases

class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'
    paginate_by = 2

class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')

class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')

class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang= es>
    <head>

        {% block extrahead %}
        {% endblock %}

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <meta charset="UTF-8">
        <title>{% block title %} Document {% endblock %}</title>
    </head>
    <body>
        
        {% block header %}
        <h4>Este es el bloque del header base</h4>
        {% endblock %}

        {% block content %}
        <h5>Este es el contenido del archivo base</h5>
        {% endblock %}

        {% block footer %}
        <!-- <h5>Soy el footer de la base</h5> -->
        {% endblock %}

        <!-- <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script> -->

        {% block extrajs %}
        {% endblock %}


    </body>
</html>

templates/mascota/index.html
{%  extends 'base/base.html' %}

{% block title %}
    App Mascota
{% endblock %}

{% block header %}
    <h5>Este es el header del index de la app mascota</h5>
{% endblock %}

{% block content %}
    <h6>Soy el contenido de mascota</h6>
{% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <h3>Desea eliminar a {{ object.nombre }}</h3>
        {{ form.as_p }}
        <button class="btm btn-danger" type="submit">Si, eliminar</button>
        <a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a> 
    </form>

{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}


    <!--En caso de querer realizar pruebas para guardar datos -->
    <form method="post">
        {% csrf_token %}

            <div class="form-group">
                <label for="form.nombre.name">{{form.nombre.label}}</label>
                {{form.nombre}}
            </div>
        <button type="submit">Guardar</button> 
    </form>

    <!-- Una forma de traer el formulario 
        {{ form.as_p }}
    -->

{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}

<!-- Esto es para listar datos de una bd -->

<table class="table table-bordered">
    <thead>
        <tr>
            <td>#</td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Edad</td>
            <td>Fecha de Rescate</td>
            <td>Adoptante</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
        {% for mascota in object_list %}
        <tr>
            <td> {{ mascota.id }}               </td>
            <td> {{ mascota.nombre }}           </td>
            <td> {{ mascota.sexo }}             </td>
            <td> {{ mascota.edad_aproximada }}  </td>
            <td> {{ mascota.fecha_rescate  }}   </td>
            <td> {{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'mascota:mascota_editar'   mascota.id%}">Editar</a>
                <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id%}">Eliminar</a>
            </td>
        </tr>
        {% endfor %}
        
        {% else %}
            <h1>No hay registros de mascotas</h1>
        {% endif %}
    </tbody>
</table>

<ul class="pagination">
    <li class="page-item">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
    </li>
    <li class="page-item">
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </li>
</ul>

{% endblock %}